name: Build and Release Docker Package

on:
  push:
    branches:
      - master

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test building image.
        run: docker build --tag docker-ansible .

      - name: Run the built image.
        run: docker run --name test-container --detach --privileged --cgroupns host --volume /sys/fs/cgroup:/sys/fs/cgroup:rw docker-ansible

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image.
        run: |
          docker build -t ghcr.io/threatcode/kali-ansible-docker:latest .
          docker push ghcr.io/threatcode/kali-ansible-docker:latest
